import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${interFont.variable} ${poppins.variable} antialiased bg-[#1a1a1a] text-white`}>
        <div className="text-white lg:max-w-[90em] lg:px-[6em] lg:mx-auto px-3">
          <Navbar />
        </div>
        <main>
          <SmoothScrollProvider>{children}</SmoothScrollProvider>
        </main>
      </body>
    </html>
  );
}
